instrument/instrument.go
This commit removes some dead code and some debug logs that clutter the application's output.
=> instrument: clean up some dead code and debug logs

README.md, go.mod, go.sum, instrument/chiv5.go, internal/instrument/chiv5.go, internal/instrument/instrument.go, internal/instrument/instrument_test.go, internal/instrument/uninstrument.go, samples/server/chiv5.go
Add support for `go-chi/chi.v5` auto-instrumentation.
=> instrument: support chi.v5

RELEASING.md, internal/version/version.go
- Add a `Tag` const that holds the orchestrion tag version. It gets updated on every release.
- Update the release process
This is inspired by the dd-trace-go release process. The main goal of having the version tag in the code is to report it in the Orchestrion telemetry.
=> release: add version tag const

internal/instrument/http.go, internal/instrument/instrument_test.go, internal/instrument/uninstrument.go
Implement HTTP handlers' unwrapping when defined in composite literals. Some light refactoring in place too, in order to reduce nesting and reduce cognitive load.
=> instrument: add unwrap for HTTP handler assign

internal/typechecker/typechecker.go
Document that the type checker doesn't work with 3rd party imports currently
=> typechecker: document 3rd party limitation

internal/version/version.go
Update version in version.go
Release of 0.3.0
=> Update version in version.go

main.go
Add the possibility to print orchestrion version via `orchestrion -v`
Better UX, useful to know which features are supported.
=> cmd: add -v flag to print version

internal/instrument/instrument_test.go, internal/instrument/uninstrument.go
Add recursion when unwrapping and removing instrumentation.
fixes #49
=> instrument: unwrap recursively

internal/version/version.go
=> internal/version: v0.6.0-dev

internal/version/version.go
bump dev version as we released v0.6
=> internal/version: v0.7.0-dev

README.md, _integration-tests/go.mod, _integration-tests/go.sum, _integration-tests/tests/chi.v5/main.go, _integration-tests/tests/echo.v4/main.go, _integration-tests/tests/gin/main.go, _integration-tests/tests/grpc/main.go, _integration-tests/tests/mux/main.go, _integration-tests/tests/net_http/main.go, _integration-tests/tests/net_http_ddspan/main.go, _integration-tests/tests/sql/main.go, go.mod, go.sum, internal/injector/testdata/injector.yml
Additionally address a couple innocent warnings found in the integration test entry points.
Fixes #50
=> chore: test dot imports are supported

.gitignore
=> (chore): gitignore swap files & orchestrion bin

internal/injector/injector.go
In some circumstances, line numbering preservation could miss emitting a directive when a regular node is nested within a synthetic node (i.e: at a function call parameter location). This fixes that, and also tweaks blank line insertion to better preserve the original file layout.
NB - this isn't tested directly here but was designed to address an issue identified when writing tests for #103.
=> fix: line numbering glitch

_integration-tests/validator/validator.go
Test is flaky due to inconsistent ordering of spans in some cases. Sorting them by start time does not help in case both spans start at the same time (on systems where the clock resolution is not sufficient to distinguish very close calls).
=> chore: fix gorm's integration test flakiness

.github/workflows/ossf-scorecard.yml
Adds the GitHub Action necessary to obtain an OpenSSF Score Card.
=> chore: create OpenSSF Score Card

internal/version/version.go
Release v0.7.4 or Orchestrion.
=> release: v0.7.4

_integration-tests/go.mod, _integration-tests/go.sum, go.mod, go.sum, internal/version/version.go, samples/go.mod, samples/go.sum
Upgrade dd-trace-go to v1.68.0 and release v0.8.1
=> release: v0.8.1

internal/version/version.go
Introduces the initial version of CI visibility instrumentation.
=> release: v0.9.3

README.md
This PR updates the Readme.md file to include the `testing` aspect
=> Adding testing aspect to README.md

main_test.go
This PR adds benchmarks for building test packages.
=> tests: add benchmark for building test packages

_integration-tests/tests/net_http/base.go, _integration-tests/tests/net_http/gen_test.go, _integration-tests/tests/net_http/serve_mux_handler.go
Fixes https://github.com/DataDog/orchestrion/issues/445
=> test: integration test for `net/http.DefaultServeMux`

internal/injector/builtin/generated_deps.go, internal/injector/builtin/yaml/stdlib/database-sql.yml
=> fix(injector: database-sql): add missing database/sql/driver import

internal/version/version.go
This release includes significant performance improvements.
=> release: v1.3.0

_docs/go.mod, _docs/go.sum, instrument/go.mod, instrument/go.sum, internal/version/version.go, samples/go.mod, samples/go.sum
=> release: v1.4.0-rc.2

internal/pin/importset.go, samples/orchestrion.tool.go
=> chore: correct typoes

_docs/go.mod, _docs/go.sum, instrument/go.mod, instrument/go.sum, internal/pin/pin.go, internal/version/version.go, samples/go.mod, samples/go.sum
=> release: v1.4.0

_docs/content/docs/configuration.md, _docs/content/docs/dd-trace-go/custom-trace.md
This PR creates a first draft of a documentation on how to dive deeper in managing your integration with orchestrion tooling
=> docs: configuration

internal/docs/adr/0002-aspect-application-order.md
Signed-off-by: Kemal Akkoyun <kemal.akkoyun@datadoghq.com>
=> docs(adr): Capture Aspect Application Order decision
