README.md, go.mod, go.sum, instrument/gorilla.go, internal/instrument/gorilla.go, internal/instrument/gorilla_test.go, internal/instrument/instrument.go, internal/instrument/uninstrument.go, samples/server/gorilla.go
Support `github.com/gorilla/mux` by detecting the instantiation of `mux.NewRouter` and replacing it with the Gorilla wrapper from `dd-trace-go`.
[Trace in DDev](https://dddev.datadoghq.com/apm/trace/4173493714106437496?colorBy=service&env=dario.castane&graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=4173493714106437496&spanViewType=metadata&timeHint=1692870785780.177)
=> instrument: support gorilla/mux

internal/version/version.go
Updates to `v0.5.0-dev` because of `v0.4.0` release.
Pending fixes blocking TEE tests.
=> internal/version/version.go: release v0.4.0

_integration-tests/tests/net_http/validation.json, instrument/http.go
Adds missing tags `span.kind` and `component` for `net/http` autoinstrumentation using `instrument.WrapHandlerFunc`.
The root cause is that it uses `httptrace.TraceAndServe` under the hood, that assumes these tags are added by the caller (like `httptrace.WrapHandler`).
=> instrument/http: add span.kind & component tags to WrapHandlerFunc

internal/instrument/chiv5.go, internal/instrument/chiv5_test.go, internal/instrument/echov4.go, internal/instrument/echov4_test.go, internal/instrument/gin.go, internal/instrument/gin_test.go, internal/instrument/instrument.go, samples/server/echov4.go
Add support for using middlewares when the server is a struct field. Before this fix, Orchestrion would inject a nil statement which causes a panic in `ast.Walk`.
fixes #51 
This commit has also been tested against https://github.com/gotenberg/gotenberg as mentioned in the issue.
=> instrument: support middleware as selector expression

_integration-tests/validator/validator.go
Fixes an error in calls to `fmt.Printf` where there were not as many arguments provided as `%` placeholders in the format string.
=> fix: Missing argument to fmt.Printf

.github/workflows/tests.yaml
- Updates gitHub Actions to current latest majors, in order to stop using deprecated Node release.
- Makes the `test.yaml` workflow compatible with GitHub merge queues
- Add a "complete" job that serves as a join point for all tests so branch protection can be easily configured to require all tests to have passed
- Correctly order `actions/checkout` and `actions/setup-go` so that the go module cache can actually be retrieved from GitHub Actions Cache 
- Make `actions/setup-go` cache configuration me mondful of there possibly being multiple `go.sum` files in the repository
=> chore: improve GitHub Workflows a bit

internal/ensure/integration/main.go, internal/ensure/integration_test.go, internal/ensure/requiredversion.go, internal/ensure/requiredversion_test.go
This PR introduces a feature that'd allow replacing the current process with a new one that runs from `go run github.com/datadog/orchestrion` so that it uses the same version as is declared in `go.mod`, allowing `orchestrion` to be installed using `go install` while still enforcing reproductible builds via `go.mod` locking.
=> feat: ensure version run matches go.mod requirements

internal/goproxy/proxy.go, internal/toolexec/proxy/proxy.go, main.go
The go build toolchain calls tooling with `-V=full` to compute the full build ID, allowing for invalidation of cached build artifacts when tooling changes.
The contract for this option is to print a single line of content, which will be embedded in the build ID. We are hence intercepting these in the `-toolexec` flow and appending the Orchestrion version and ruleset information to the output.
---
Additionally, this removes ability to force build (pass `-a`) and override the `GOCACHE`, since these measure ought to make these two features redundant.
=> feat: decorate output of `toolexec [...] -V=full`

internal/toolexec/examples/add-go-file.go, internal/toolexec/examples/list-go-files.go, internal/toolexec/examples/replace-go-file.go, internal/toolexec/processors/fileswap.go, internal/toolexec/processors/package.go, internal/toolexec/proxy/proxy.go
This makes it easier to manage errors in `-toolexec` processors, and also provides a clean and easy way to report that a given command should be skipped instead of being run.
=> feat: allow command processors to return an error

tools.go
In order to better inter-operate with `go mod vendor`, add a blank import on `github.com/datadog/orchestrion/instrument` so that package (and its dependencies) is not pruned by `go mod vendor` for not being explicitly required.
=> fix: blank import `./instruments` in `tools.go`

internal/injector/aspect/advice/block.go
The error message produced in case when an advice is used on an incompatible join-point output the type name `*node.Chain` instead of the actual underlying node type name... This fixes that issue to make the error message more useful.
=> fix: error message shows useless expectation

internal/injector/aspect/join/function.go
This change avoids having to change every option's `evaluate` signature each time a new piece of information is needed when implementing a new option. This is a significant quality-of-life improvement.
=> refactor: improve API for `FunctionOption`

internal/toolexec/aspect/oncompile-main.go, internal/toolexec/aspect/oncompile.go, internal/toolexec/proxy/compile.go, main.go
Go's `linker` does not bring in all objects from the `importcfg` file unconditionally, instead it only loads objects (transitively) **imported** by the `main` module. This means that _linkDeps_ introduced to satisfy `//go:linkname` directives may not be satisfied by the linker (resulting in undefined symbol errors) unless those dependencies are imported.
This change adds an `OnCompileMain` transformer to the `Weaver` that adds a new synthetic source file that contains blank imports of any yet-to-be-satisfied _linkDeps_ entry, ensuring the linker later satisfies them. It also has the benefit of making sure the compiler correctly registers any `init` function from these dependencies on the start-up stack.
This ought to be safe to do in `main`, since this cannot possibly introduce circular …
=> fix: linker may fail to satisfy linkdeps unless imported by main

.github/workflows/tests.yml, .gitignore, codecov.yml, integration-tests.ps1
Keep an eye on code coverage to ensure consistent quality standard.
Coverage samples are sent to codecov, and tagged by:
- OS
- Test type (unit / integration)
- Go version
=> chore: collect & upload code coverage

.github/workflows/generate.yml, .github/workflows/tests.yml, codecov.yml
This will help get a better visibility on the real code coverage, granted a number of code paths only exist for generators to use.
=> chore: collect coverage when running generators

.github/workflows/release.yml
Adds a new workflow that triggers on modifications to the `internal/version.go` file, and determines whether a new release should be created or not.
If the version tag does not match an existing release:
- on `pull_request`, requires the PR title be set to `release: <tag>`
- on `push`, automatically creates a _draft_ release with the corresponding tag
This allows automating release creation by simply merging a pull request that updates the `Tag` constant in `internal/version.go` and limits the risk of incorrectly cutting releases.
=> chore: workflow for automated release creation

.github/workflows/release.yml, internal/version/version.go, pin_test.go
Release `v0.7.2`.
Additionally, fixes:
- Some issues with the release automation (fixing the PR title comparison, fixing the `version.go` file path)
- An issue with the `pin`/`autoPin` test that causes it to fail because the current release tag does not _yet_ exist
- Checking for existing release when appropriate to catch user error early
=> release: v0.7.2

.github/workflows/docsite.yml
The datadoghq.dev site is served with CloudFlare auto-minification, which breaks SRI attributes if the minification performed by Hugo is not identical to that of CloudFlare.
In order to avoid this issue, disable SRI output in the website build by setting the environment to something other than `production`.
=> fix: broken documentation site

.github/workflows/docsite.yml
Filtering on the `paths` does not work all too well with merge queues, as the filter only looks at the top-most commit being pushed, instead of the superposition of all new commits.
=> chore: republish docsite on all `main` pushes

.github/workflows/release.yml, RELEASING.md
In non-interactive mode, the command must include the tag name to create as a positional argument.
---
Also edits `RElEASING.md` to reflect simplified release process.
=> chore: correct `gh release create` command, edit RELEASING.md

README.md
The orchestrion image made the first look at our repo look and feel complex while it's not. So I removed it in favor of a more discreet wikipedia link in the first orchestrion word of the overview section.
=> docs: friendlier landing repo page

docs/layouts/shortcodes/godoc.html
The links to pkg.go.dev were broken due to mismatched quotation marks,
mixing single and double quotes. This lead to the "target" and "rel"
attributes getting added to the actual URL, like
https://pkg.go.dev/net/http#Server" target="_blank" rel="noopener
See, for example, the link to the `net/http.Server` docs on
https://datadoghq.dev/orchestrion/docs/built-in/stdlib/net-http.server/:
=> docs: fix broken pkg.go.dev links

docs/content/contributing/aspects/code-templates.md, internal/injector/aspect/advice/code/dot_ast.proxies.go, internal/injector/aspect/advice/code/generator/main.go
The code template documentation incorrectly stated that using `.AST` results in copying nodes; while this is not the case. Corrected the wording and added a `.Copy` method to actually have a way to copy AST nodes instead of only being able to move them.
=> docs: correct error in code template documentation

.github/workflows/docsite.yml, .github/workflows/generate.yml, .github/workflows/release.yml, .github/workflows/tests.yml, README.md
Reduce vulnerable surface of the repository by enacting recommendations from the OpenSSD Scorecard:
- Set default read-only permissions at the top-level of all GitHub workflows;
- Avoid possible shell injection via event inputs by indirecting values through environment variables.
=> chore: improve OpenSSF Score

.github/workflows/workflow_call.yml
This PR creates a new workflow because we can't use the codecov workflow in dd-trace-go. Even if we are not technically using it because the `if` condition would have evaluated to false. cf. [this job](https://github.com/DataDog/dd-trace-go/actions/runs/9892772923)
Add a CI connection dd-trace-go and orchestrion to make sure we don't break orchestrion features when changing dd-trace-go
=> ci: setup reusable workflow for integration tests

.github/workflows/release.yml, README.md, _integration-tests/validator/trace/diff.go, _integration-tests/validator/trace/span.go, internal/injector/aspect/advice/code/template.go, internal/injector/aspect/advice/code/template_test.go, internal/injector/aspect/advice/code/testdata/parse_error.txt, internal/version/version.go
Contains a small set of misc. fixes:
- Adjusted the `release.yml` workflow to account for the new output format of `orchestrion version`
- Updated `README.md` to mention supported contribs with minimum Orchestrion version (note that it intentionally does not include prerelease identifiers in the versions)
- Change all cases of length-adjusted format strings to use `%-*s`/`% *d` instead of previously using `fmt.Sprintf` to craft the format string; which is probably quite a bit safer
- Added a test case that leverages the `numberLines` function in `code.Template` as it was previously uncovered by tests & this change touched it
- Fix tab-indentation replacement in the `code.Template` doc-gen to only replace two-space indents with tabs at line start (previously anywhere on the line)
=> release: v0.7.4-rc.2

main.go
Add hidden flags to enable profiling Orchestrion. Options for writing
CPU and heap profiler, as well as execution traces, with a configurable
path prefix. Enabling the profiler for the parent enables it for the
children. There is one of each enabled profile type per process, and
each file gets the PID in its name.
Note that CPU profiling adds a ~200ms delay at the end of the app to
stop profiling. This might matter more for Orchestrion since there are
many normally short-lived processes.
Execution tracing should be enabled with caution since traces can be
quite large. Even the other profile types can produce significant
amounts of data. The profiles will have redundant symbol data. The CPU
and heap profiles can be combined into a single profile to eliminate the
redundancy.
Example usage: …
=> feat: add profiling of Orchestrion

main.go
If the log level is set via `--log-level`, set the corresponding environment
variables so that the child processes will get it. This was done for
`--log-file` already, but only if it was originally a relative path. Propagate
it always.
I noticed this when investigating #223. I was setting the log level to "trace"
via the command line and didn't see much output. It took me a bit to realize
that the setting wasn't picked up by all the workers. I set the env var
instead, but ideally the command line argument works the
same way :)
=> fix: propagate --log-level and --log-file to child processes

.github/workflows/deps-update.yml, .github/workflows/docsite.yml, .github/workflows/generate.yml, .github/workflows/release.yml, .github/workflows/tests.yml, .github/workflows/workflow_call.yml
This allows us to never have to change our workflow configuration when a new go release is issued, as these labels automatically resolve via the published release manifest.
Also uses `go.mod` files instead of `go.sum` files to compute cache keys, as the `go.sum` files are technically not a dependency manifest.
=> chore: use oldstable and stable for running workflows

internal/ensure/requiredversion.go, internal/injector/injector.go, internal/jobserver/buildid/version.go, internal/jobserver/pkgs/resolve.go
This allows to get more debugging information with the TRACE log level.
=> chore: uniformly pass log.Tracef as packages.Load logger

internal/ensure/requiredversion_test.go, internal/goenv/gobin.go, internal/goenv/gobin_test.go, internal/goflags/flags.go, internal/goflags/flags_test.go, internal/goflags/quoted/quoted.go, internal/goflags/quoted/quoted_test.go, internal/goproxy/dashc.go, internal/goproxy/proxy.go
In order to properly convey coverage flags to child processes when doing injected package resolution, it is important the `-cover` flags only applies to packages selected for instrumentation by the user, otherwise some packages may be instrumented or not instrumented depending on whether they are directly resolved or a transitive dependency of a directly resolved package; and this leads to link-time fingerprint mismatches.
This implies we must make the default value of `-coverpkg` explicit if it is not provided by the user.
=> fix(goflags): using `-cover` causes fingerprint mismatch

README.md, docs/config/_default/hugo.toml, docs/content/docs/built-in/_index.md, docs/content/docs/custom-trace.md, docs/content/docs/features.md, docs/content/docs/getting-started.md
Added:
- Feature activation documentation (Tracer, Profiler, ASM)
- Trace customization (`//dd:span`, `//dd:ignore`)
Removed:
- Details from `README.md`, replaced with pointers to the user guide
=> docs: improvements to the user guide

.github/actions/codecov-upload/action.yml, .github/workflows/validate.yml
Bash treats arrays as defined only if at least one index has been assigned a value, meaning empty arrays are treated as undefined, which trips when `set -u` is being used. The safe idiom to use in this case is `${arr[@]+"${arr[@]}"}`, which only tries expanding the array if it is deemed set. This is not very pretty, but should do the deed.
=> chore: make array expansions empty-safe

_integration-tests/utils/testcontainers.go
Now that integration tests are in separate packages, tests are no longer running sequentially, so since both aws v1 and v2 tests use this container, we should not be setting a name and instead let testcontainers generate it.
=> fix: do not set container name for dynamodb

internal/injector/aspect/context/node.go, internal/injector/injector.go, internal/injector/restorer.go, internal/jobserver/pkgs/resolve.go
Instrumentation of source files can be performed in parallel, as the AST transformations do not span across files. Once the files are parsed & type checked, using a distinct decorator per file enables parallel processing & more efficient post-processing (fewer items in the decorator maps, none of which irrelevant to the current AST being post-processed).
This would improve the performance of builds, and a local profile showed a 70% improvement on the specific package I was playing with.
=> feat: instrument source files in parallel

docs/content/contributing/performance.md
Provides a basic guide on how to get started with the built-in `--profile-path` and `--profile` flags of orchestrion when performing performance investigation.
=> docs: getting started with orchestrion built-in profiling

internal/injector/imports.go, internal/injector/imports_test.go, internal/injector/injector.go, internal/injector/write.go, tools/headercheck/header_check.go
=> fix(injector): nil-dereference on a specific import order

.github/workflows/validate.yml
The concurrency group naming results in cancelling concurrent executions on the same ref on all events, which means individual commits pushed to `main` may not be fully validated. In particular, this results in missing coverage information & benchmarking results.
Changed the naming so that on `push` events, the commit SHA is used instead of the commit ref, allowing individual commits to run independently from each other.
=> chore: allow validation to run for ALL commits on push

.github/workflows/deps-update.yml
The procedure to create the PR requires the branch is checked out, but the work tree is dirty at time of doing so; as the commit is created from the dirty files via the GitHub API. Clean up the working copy before switching to the newly created commit.
=> chore: dependency upgrade workflow fails

_integration-tests/go.mod, _integration-tests/go.sum, go.mod, go.sum, internal/version/version.go, samples/go.mod, samples/go.sum
=> release: v0.9.2

.github/actions/codecov-cli/action.yml, .github/actions/codecov-cli/requirements-dev.txt, .github/dependabot.yml, .github/workflows/validate.yml, .github/workflows/workflow_call.yml, _integration-tests/README.md, _integration-tests/tests/gcp_pubsub/gcp_pubsub.go, _integration-tests/utils/agent/agent.go, _integration-tests/utils/agent/requirements-dev.txt
The reasoning is I hope this reduces flakiness, assuming it is caused at least in parts by our test containers running against runner resource limits.
This implies:
- Switching to the `arm-4core-linux` runner
- Installing `docker` on those new runners (not there by default)
- Installing `build-essential` on those new runners (required for CGO, which sqlite3 needs)
- Switching the image used by the GCP pubsub tests, as the one that was used was the older, deprecated one; which does not support `linux/arm64` platforms, in favor of the new, maintained one which does support it
=> chore: use larger runners for linux integration tests

README.md, _integration-tests/go.mod, _integration-tests/go.sum, go.mod, go.sum, internal/toolexec/version_test.go, internal/version/version.go, samples/go.mod, samples/go.sum
Upgrades dd-trace-go to `v1.69.1-rc.4`.
=> release: v0.9.4-rc.1

internal/injector/builtin/generated.go, internal/injector/builtin/testdata/client/redis.go.snap, internal/injector/builtin/yaml/databases/redigo.yml
Fix badly used import creating this error
```
❯ orchestrion go test ./... -work           
WORK=/var/folders/42/00hrt9gj3276cy8h0_d9nw480000gq/T/go-build1245716950
/Users/tony.redondo/go/pkg/mod/go.ddbuild.io/dd-source/x@v0.0.0-20241021135812-b13784d37c9c/libs/go/redis/connector.go:40: undefined: redis
exit status 2
```
=> fix(injector: redigo) undefined: redis

docs/content/contributing/aspects/code-templates.md, docs/content/contributing/aspects/guidelines.md, docs/content/docs/custom-trace.md, docs/content/docs/features.md
Incorrect use of the godoc shortcode resulted in blank links being rendered.
=> fix: blank links in documentation

internal/ensure/requiredversion.go, internal/ensure/requiredversion_test.go, internal/pin/pin.go, internal/pin/pin_test.go
Fixes #371 
See https://github.com/golang/go/issues/65816
=> fix(ensure): packages.Load().Module is nil

internal/pin/gomod.go, internal/pin/pin.go, main.go
The documentation for `os.IsNotExist` states:
> This function predates [errors.Is](https://pkg.go.dev/errors#Is). It only supports errors returned by the os package. New code should use `errors.Is(err, fs.ErrNotExist)`.
=> chore: standardize on `errors.Is(err, fs.ErrNotExist)`

README.md, _integration-tests/tests/chi.v5/chi.go, _integration-tests/tests/gcp_pubsub/gcp_pubsub.go, docs/content/docs/_index.md, docs/content/docs/custom-trace.md, docs/content/docs/features.md, docs/layouts/partials/navbar.html, internal/injector/injector.go, internal/injector/labels.go, internal/injector/testdata/injector/http-ignored/config.yml
The `//orchestrion:ignore` directive replaces `//dd:ignore` to make it clear that it opts the node tree out of any orchestrion processing, and not just of datadog integrations.
The `dd:ignore` directive continues to work, but a warning will be emitted when it is encountered, prompting users to update their code.
=> feat: rename `dd:ignore` to `orchestrion:ignore`

instrument/instrument.go, internal/binpath/cmd.go, internal/cmd/go.go, internal/cmd/toolexec.go, internal/goflags/flags.go, internal/goproxy/proxy.go, internal/jobserver/buildid/version.go, internal/jobserver/client/env.go, internal/jobserver/pkgs/resolve.go, internal/jobserver/pkgs/resolve_test.go, internal/toolexec/aspect/resolve.go
In certain conditions, using `-tags` that affect injected packages, such as `-tags=appsec` when `CGO_ENABLED=0` results in a fingerprint mismatch at link time, due to the go build flags being incorrectly discovered.
This is fixed by making several changes:
- Changes how the "shared" build flags are set in the job server's `pkgs.Resolve` operation, so that they are resolved during execution, instead of when creating the request; ensuring the pre-set flags are used in cases where "driver mode" is used;
- Actively parse `-a` and `-toolexec` from go process args, so we explicitly prevent them from being forwarded (`-a` in particular causes builds to be A LOT slower due to re-building many injected packages over and over again);
- Adds trace logging here and there to make this type of issues a …
=> fix: fingerprint mismatch when using `-tags` that affect injected packages

internal/version/version.go
Includes a bug fix for an occasional `fingerprint mismatch` during `link`.
=> release: v1.0.1

internal/injector/builtin/yaml/stdlib/net-http.server.yml
`orchestrion` doesn't do auto-instrumentation for this code because `handler` in [http.ListenAndServe()](https://github.com/golang/go/blob/c5adb8216968be46bd11f7b7360a7c8bde1258d9/src/net/http/server.go#L3650-L3660) is set to `nil`. Setting `nil` in `http.ListenAndServe()` is generally a common practice.
```go
package main
import (
"context"
"log/slog"
"net/http"
"os"
"os/signal"
)
func main() {
ctx, cancel := signal.NotifyContext(context.Background(), os.Interrupt)
defer cancel()
http.HandleFunc("/hello", func(w http.ResponseWriter, r *http.Request) {
slog.InfoContext(r.Context(), "Request received at /hello")
resp, err := http.Get("https://example.com")
if err != nil {
http.Error(w, err.Error(), http.StatusInternalServerError)
return
}
defer resp.Body.Close() …
```
=> feat: support auto-instrumentation when `net/http.DefaultServeMux` is used implicitly

internal/injector/aspect/context/context.go, internal/injector/check.go, internal/injector/injector.go, internal/injector/testdata/injector/chi5-newroute-dotimport/config.yml, internal/injector/testdata/injector/import-shadowing/config.yml, internal/injector/testdata/injector/import-shadowing/expected.diff, internal/injector/typed/refmap.go
Previously we would only check if the import was present in a fix. Now, we are checking if import is accessible as the import we are looking for.
Fixes #458
Fixes #448
=> fix(injector): source import shadowed results in build error "X is not a type"

internal/injector/aspect/advice/assign.go, internal/injector/aspect/advice/block.go, internal/injector/aspect/advice/call.go, internal/injector/aspect/advice/inject.go, internal/injector/aspect/advice/wrap.go, internal/injector/injector.go
Provide more context information in the error messages propagated from advice application errors, so that they are easier to troubleshoot. These messages aim to provide a lineage that allows maintainers to know exactly what advice failed, on what file.
=> feat: improve context in error advice messages

internal/toolexec/aspect/oncompile.go, main_test.go
Load the configuration from the module root instead of the current working directory, so that it no longer fails when building a package in a sub-directory.
Fixes #464
=> fix: orchestrion fail to instrument if is not in the go.mod folder

internal/goflags/flags.go
When running orchestrion in a Docker container using a Rosetta-backed engine (using the `vz` type of VM), the `argv0` found when crawling process trees is the `binfmt` handler (`rosetta`) instead of the actual command being executed.
The `rosetta` handler is only present on the hypervisor (hence it fails on `no such file or directory` during resolution attempts). When encountering not found errors on `linux/amd64` platforms, where the binary name is `rosetta`, try to resolve `argv[1]` as a fallback.
=> fix: failed to resolve argv0 ("/run/rosetta/rosetta")

_integration-tests/tests/ibm_sarama/ibm_sarama.go, _integration-tests/tests/segmentio_kafka.v0/segmentio_kafka.go, _integration-tests/utils/backoff/backoff.go, _integration-tests/utils/backoff/backoff_test.go, _integration-tests/utils/backoff/constant.go, _integration-tests/utils/backoff/exponential.go, _integration-tests/utils/backoff/exponential_test.go
The segmentio_kafka test has been falking due to the test container not having the topic and partition ready by the time the test tries to produce messages. This is possiblye due to the test waiting up to 1 second, while the container has been observed to need almost 2 seconds to transition the initial partition to available.
=> chore: exponential backoff in flaky kafka test

README.md, _integration-tests/tests/redigo/redigo.go
There needs to e a blank line before anchors are defined.
=> docs: fix anchor definition in README.md

internal/cmd/toolexec.go, internal/toolexec/aspect/linkdeps/linkdeps.go, internal/toolexec/aspect/oncompile-main.go, internal/toolexec/aspect/oncompile.go, internal/toolexec/proxy/compile.go, internal/toolexec/proxy/proxy.go
The `OnCompile` hook cannot necessarily resolve the transitive dependencies of all link-time dependencies, as those are normally used to avoid creating dependency cycles.
The `OnCompileMain` hook however MUST resolve the transitive dependencies of everything, as it needs to introduce `import`s of all synthetic link-time dependencies so that they are correctly registered (their `init` functions get scheduled, and they get presented to the linker). This was previously not necessarily done, and could result in link-time failures.
---
This involved re-working the way the `link.deps` file is added to the `_pkg_.a` files so that both the `OnCompile` and `OnCompileMain` functions contribute to the same closure and it gets written & registered exactly once. As a result `Command.OnClose` was …
=> fix: OnCompileMain needs to register new `link.deps`

.github/workflows/validate.yml, go.mod, internal/cmd/server.go, internal/cmd/toolexec.go, internal/files/files.go, internal/goflags/flags.go, internal/jobserver/buildid/version.go, internal/jobserver/client/client.go, internal/jobserver/client/env.go, internal/jobserver/common/handler.go, internal/jobserver/nbt/nbt.go, internal/jobserver/nbt/nbt_test.go, internal/jobserver/pkgs/resolve.go, internal/jobserver/pkgs/resolve_test.go, internal/jobserver/server.go, internal/toolexec/aspect/oncompile.go, internal/toolexec/aspect/resolve.go, internal/toolexec/proxy/compile.flags.go, internal/toolexec/proxy/compile.go, internal/toolexec/proxy/compile_test.go, internal/toolexec/proxy/errors.go, internal/toolexec/proxy/link.go, internal/toolexec/proxy/link_test.go, internal/toolexec/proxy/parse.go, internal/toolexec/proxy/proxy.go, internal/toolexec/proxy/proxy_test.go, internal/toolexec/version.go, internal/toolexec/version_test.go, main.go
Adds a new jobserver message to track ongoing compilation tasks, so that duplicates can be completely avoided by re-using the first build task's outcome. This allows de-duplicating builds even if an injected package is already present in the natural dependency closure of the package being built.
Fixes #430
=> feat: never build twice

.github/workflows/docsite.yml
The documentation generation workflow was failing because it still referred to the `go generate` task from the old built-ins package.
=> chore: fix doc generation workflow

internal/goflags/flags.go, internal/goflags/flags_test.go, internal/pin/pin.go
The value of `-coverpkg` is only inferred when `-cover` is passed, but passing `-covermode` implies `-cover`. This change checks both `-cover` and `-covermode` presence to decide whether to infer `-coverpkg` or not.
Fixes #526
=> fix: build ID mismatch when using `-covermode` without `-cover`

internal/injector/config/config-go.go, internal/injector/config/config_test.go, internal/jobserver/buildid/version.go
Better error messages for cases like #535
=> fix(injector: config): better error message when orchestrion.tool.go is missing

internal/injector/aspect/join/directive.go, internal/injector/aspect/join/directive_test.go
The `//dd:span` directive is not honored when it's presented on a `return` statement (where the expression is a literal function expression).
This changes the directive lookup function so it crawls up to the parent if it's a node type that wraps a single expression; effectively:
- `name := <expr>` (LHS and RHS)
- `name = <expr>` (RHS only)
- `<call>` (function portion only)
- `defer <call>`
- `<expr>` (the expression statement)
- `go <expr>`
- `return <expr>`
- `ch <- <expr>` (the value only)
Fixes #539
=> fix: pragma directives not picked up on return statement

internal/toolexec/aspect/oncompile.go
Avoid circular instrumentation of dd-trace-go V2 by applying the `tracer-internal-only` treatment to the root namespace while still allowing the integration test suite there to be woven into.
=> chore: apply tracer-internal-only to dd-trace-go V2

_docs/generator/main.go, _docs/generator/schema.go, _docs/go.mod
This was restored from https://github.com/DataDog/orchestrion/blob/c5b11d00b413f09687830f90b32f4a986e82eefe/internal/injector/builtin/generator/schema.go
=> docs: restore generated docs for join points & advice

internal/injector/aspect/advice/struct.go, internal/injector/testdata/injector/add-struct-field/config.yml, internal/injector/testdata/injector/add-struct-field/modified.go.snap
Whena dding a new field to a struct, the package containing the type of the field may need importing, which was not previously done.
=> fix: add-struct-field does not implicitly import the type's package

internal/injector/config/builtin.go, internal/injector/config/config_test.go, internal/injector/config/testdata/instrument.snap.yml, internal/injector/config/testdata/required.snap.yml, runtime/built/built.go, runtime/built/built_test.go
Introduce a new //orchestrion:version pragma to
allow run-time determination of the orchestrion
version that built a given binary.
This would be useful to implement telemetry directly
in the tracer so it is reliably sent even when the
tracer is not started by orchestrion itself.
=> feat: new //orchestrion:version pragma

internal/injector/aspect/join/function.go, internal/injector/aspect/join/function_test.go, internal/injector/testdata/injector/signature-contains/config.yml, internal/injector/testdata/injector/signature-contains/modified.go.snap
Adds flexible function signature matching to support partial and order-independent type matching. 
This enables simpler instrumentation configuration when targeting functions that share common types (e.g. context.Context or error) regardless of their position or other parameters. 
The change simplifies instrumentation configuration by reducing the need for multiple matchers when targeting related function groups
- Added SignatureContains matcher that checks for presence of types anywhere in function signatures
- Supports matching on partial argument/return types without requiring exact matches
- Added tests
=> chore(join/function): Add tests to signature-contains

internal/injector/aspect/join/function.go, internal/injector/aspect/join/function_test.go, internal/injector/testdata/injector/signature-contains/config.yml, internal/injector/testdata/injector/signature-contains/modified.go.snap
Adds flexible function signature matching to support partial and order-independent type matching. 
This enables simpler instrumentation configuration when targeting functions that share common types (e.g. context.Context or error) regardless of their position or other parameters. 
The change simplifies instrumentation configuration by reducing the need for multiple matchers when targeting related function groups
- Added SignatureContains matcher that checks for presence of types anywhere in function signatures
- Supports matching on partial argument/return types without requiring exact matches
- Added tests
=> feat(injector: join): signature-contains

.editorconfig, internal/jobserver/buildid/version.go, internal/toolexec/version_test.go
When a `go.mod` file contains a `replace` directive for a module that is part of the current workspace (and directing to the in-workspace directory), the `go list` command does not return a `Replace` field for that module; instead it returns a blank `Version` field.
This commit fixes the file fingerprinting decision so that it hashes the modules' content when the `Version` field is blank or when the module is replaced by a local directory.
Also added a unit test to validate things work as expected in this case.
=> fix: fingerprint mismatch when using go.work files

internal/version/version.go
This release fixes an issue with fingerprint mismatches when using a `go.work` file.
=> release: v1.3.1

.github/workflows/release.yml
GitHub's (un-documented) algorithm for automatically selecting the previous release tag when generating release notes appears to be hindered by the presence of our nested go module tags. So we explicitly select the previous non-pre, non-draft release as the previous tag.
=> chore: fix release previous tag auto-selection

_tools/conventionalcommit/main.go
Added detailed comments to the conventionalLabels map in main.go to clarify the purpose of each conventional commit type and its corresponding label. This improves code readability and understanding of the mapping between commit types and labels.
Signed-off-by: Kemal Akkoyun <kemal.akkoyun@datadoghq.com>
=> chore: enhance conventionalLabels with detailed comments

internal/injector/aspect/join/join.go, internal/injector/aspect/join/join_test.go
This PR allows Orchestrion's `function` join point to correctly match methods on receivers that are instantiations of generic types (e.g., `*MyType[T]`).
Currently, when a method receiver is a generic type like `*MyType[T]`, the Go AST structure is more complex than a simple identifier. For `github.com/dave/dst` nodes, it looks something like this:
```
*dst.StarExpr (represents the '*')
└── X: *dst.IndexExpr (represents MyType[T])
├── X: *dst.Ident (represents MyType - the base generic type)
└── Index: *dst.Ident (represents T - the type parameter)
```
(For multiple type parameters like `MyType[T, U]`, it would be `*dst.IndexListExpr` with multiple `Indices`).
However, the existing `join.TypeName.Matches` method lacked the necessary cases to handle the `*dst.IndexExpr` or …
=> feat(injector): Support generic join point types

.gitignore, internal/injector/aspect/advice/code/dot_function.go, internal/injector/aspect/advice/code/dot_function_test.go, internal/injector/aspect/advice/code/template_test.go, internal/injector/aspect/context/context.go, internal/injector/aspect/context/context_test.go, internal/injector/injector.go, internal/injector/testdata/injector/result-implements/config.yml, internal/injector/testdata/injector/result-implements/modified.go.snap
This commit introduces the capability to identify function return values that implement a specific interface within the code injection framework.
**Key Changes:**
*   **`AdviceContext.ResolveType`:** Added a new method to `AdviceContext` (`internal/injector/aspect/context/context.go`) that resolves a `dst.Expr` to its corresponding `go/types.Type`. This leverages the `types.Info` provided during analysis and handles identifiers, selectors, and pointer types.
*   **`code.ResultThatImplements` / `code.LastResultThatImplements`:** Added new functions to the `code` package (`internal/injector/aspect/advice/code/dot_function.go`) that allow advice templates to query for the first or last result parameter of the current function context that implements a given interface (specified by its string …
=> feat(injector): Add ability to find function results implementing an interface

internal/injector/typed/typecheck.go
This update refactors the `ResolveInterfaceTypeByName` function to enhance its structure and error reporting. The function now separates the logic for handling built-in types and package-qualified types, improving readability. A new helper function, `validateTypeNameIsInterface`, has been introduced to encapsulate the validation of interface types, ensuring consistent error messages and reducing code duplication.
Additionally, specific error messages have been added for import failures and type lookups, providing clearer context for users.
Signed-off-by: Kemal Akkoyun <kemal.akkoyun@datadoghq.com>
=> refactor(injector/typed): Refactor ResolveInterfaceTypeByName for improved clarity and error handling

main_test.go
Traefik fails to build with the following error:
```
webui/embed.go:10:12: pattern static: no matching files found
```
To fix it, before building, create a static folder with some mock content so go embed does not fail.
=> fix(bench): fix traefik build

internal/goflags/flags.go, internal/goflags/flags_test.go
When using `go test` and providing the test package set before some flag, the subsequent flags were not correctly processed, resulting in particular in the `-coverpkg` flag not being appropriately expanded when necessary. This resulted in relative patterns being passed to child builds which is the cause of some build ID mismatch errors.
This was caused by an incorrect assumption that all `go` building commands demand flags are presented before any positional argument, which is at least not true for `go test` (and likely also for `go run`).
=> fix: flags only partially processed

internal/injector/config/schema.json
Add four missing function options to the JSON schema that were added
in recent commits but not reflected in the schema:
- signature-contains: flexible signature matching with partial types
- result-implements: match functions with return values implementing interfaces
- final-result-implements: match functions where final return implements interface
- argument-implements: match functions with arguments implementing interfaces
Also update examples to demonstrate usage of all new function options.
All tests pass and schema validation confirms correctness.
Signed-off-by: Kemal Akkoyun <kemal.akkoyun@datadoghq.com>
=> chore(config): Add missing function options to schema.json
